### ISSUE TITLE
Fix acorn error

### ISSUE THREAD

**Issue by Applelo** [principalstudio/principal-purgecss-extractor#7]
`Since Acorn 8.0.0, options.ecmaVersion is required. Defaulting to 2020, but this will stop working in the future. 398 modules`

**Comment by PetrLaskevic** [comment]
It's interesting how this came up instead of any `acorn` docs :D 
The whole fix for anybody wondering:
```js
const acornOptions: acorn.Options = {
  ecmaVersion: 'latest', //or 2020 etc
};
const strParsed = acorn.parse('[' + str + ']', acornOptions)
```

From [acorn docs](https://github.com/acornjs/acorn/tree/master/acorn/):

> **ecmaVersion:** Indicates the ECMAScript version to parse. Can be a number, either in year (2022) or plain version number (6) form, or "latest" (the latest the library supports). This influences support for strict mode, the set of reserved words, and support for new syntax features.
